# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

use_frameworks!

target 'Restock' do
  pod "Alamofire"
  pod "SwiftyJSON"
  pod "EstimoteSDK"
  pod "SnapKit"
end

